export interface IBind {

    // Enabled
    (event: 'Enabled_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'Enabled_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // Syncing
    (event: 'Syncing_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'Syncing_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // Synced
    (event: 'Synced_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'Synced_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // Restart
    (event: 'Restart_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'Restart_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // PreparingList
    (event: 'PreparingList_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'PreparingList_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // ListReady
    (event: 'ListReady_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'ListReady_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // FetchingTasks
    (event: 'FetchingTasks_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'FetchingTasks_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // TasksFetched
    (event: 'TasksFetched_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'TasksFetched_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // TasksCached
    (event: 'TasksCached_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'TasksCached_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // SyncingThreadsToTasks
    (event: 'SyncingThreadsToTasks_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'SyncingThreadsToTasks_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // ThreadsToTasksSynced
    (event: 'ThreadsToTasksSynced_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'ThreadsToTasksSynced_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // SyncingTasksToThreads
    (event: 'SyncingTasksToThreads_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'SyncingTasksToThreads_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // TasksToThreadsSynced
    (event: 'TasksToThreadsSynced_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'TasksToThreadsSynced_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // SyncingCompletedThreads
    (event: 'SyncingCompletedThreads_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'SyncingCompletedThreads_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // CompletedThreadsSynced
    (event: 'CompletedThreadsSynced_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'CompletedThreadsSynced_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // SyncingCompletedTasks
    (event: 'SyncingCompletedTasks_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'SyncingCompletedTasks_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // CompletedTasksSynced
    (event: 'CompletedTasksSynced_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'CompletedTasksSynced_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // ThreadsFetched
    (event: 'ThreadsFetched_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'ThreadsFetched_state', listener: (/* param1, param2 */) => any, context?: Object): this;
    // MsgsFetched
    (event: 'MsgsFetched_enter', listener: (/* param1, param2 */) => boolean | undefined, context?: Object): this;
    (event: 'MsgsFetched_state', listener: (/* param1, param2 */) => any, context?: Object): this;


    // Non-params events
    (event: 'Enabled_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'Enabled_end', listener: () => any, context?: Object): this;
    (event: 'Syncing_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'Syncing_end', listener: () => any, context?: Object): this;
    (event: 'Synced_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'Synced_end', listener: () => any, context?: Object): this;
    (event: 'Restart_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'Restart_end', listener: () => any, context?: Object): this;
    (event: 'PreparingList_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'PreparingList_end', listener: () => any, context?: Object): this;
    (event: 'ListReady_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'ListReady_end', listener: () => any, context?: Object): this;
    (event: 'FetchingTasks_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'FetchingTasks_end', listener: () => any, context?: Object): this;
    (event: 'TasksFetched_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'TasksFetched_end', listener: () => any, context?: Object): this;
    (event: 'TasksCached_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'TasksCached_end', listener: () => any, context?: Object): this;
    (event: 'SyncingThreadsToTasks_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'SyncingThreadsToTasks_end', listener: () => any, context?: Object): this;
    (event: 'ThreadsToTasksSynced_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'ThreadsToTasksSynced_end', listener: () => any, context?: Object): this;
    (event: 'SyncingTasksToThreads_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'SyncingTasksToThreads_end', listener: () => any, context?: Object): this;
    (event: 'TasksToThreadsSynced_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'TasksToThreadsSynced_end', listener: () => any, context?: Object): this;
    (event: 'SyncingCompletedThreads_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'SyncingCompletedThreads_end', listener: () => any, context?: Object): this;
    (event: 'CompletedThreadsSynced_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'CompletedThreadsSynced_end', listener: () => any, context?: Object): this;
    (event: 'SyncingCompletedTasks_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'SyncingCompletedTasks_end', listener: () => any, context?: Object): this;
    (event: 'CompletedTasksSynced_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'CompletedTasksSynced_end', listener: () => any, context?: Object): this;
    (event: 'ThreadsFetched_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'ThreadsFetched_end', listener: () => any, context?: Object): this;
    (event: 'MsgsFetched_exit', listener: () => boolean | undefined, context?: Object): this;
    (event: 'MsgsFetched_end', listener: () => any, context?: Object): this;

    // Transitions

    (event: 'Enabled_Any'): this;
    (event: 'Enabled_Syncing'): this;
    (event: 'Enabled_Synced'): this;
    (event: 'Enabled_Restart'): this;
    (event: 'Enabled_PreparingList'): this;
    (event: 'Enabled_ListReady'): this;
    (event: 'Enabled_FetchingTasks'): this;
    (event: 'Enabled_TasksFetched'): this;
    (event: 'Enabled_TasksCached'): this;
    (event: 'Enabled_SyncingThreadsToTasks'): this;
    (event: 'Enabled_ThreadsToTasksSynced'): this;
    (event: 'Enabled_SyncingTasksToThreads'): this;
    (event: 'Enabled_TasksToThreadsSynced'): this;
    (event: 'Enabled_SyncingCompletedThreads'): this;
    (event: 'Enabled_CompletedThreadsSynced'): this;
    (event: 'Enabled_SyncingCompletedTasks'): this;
    (event: 'Enabled_CompletedTasksSynced'): this;
    (event: 'Enabled_ThreadsFetched'): this;
    (event: 'Enabled_MsgsFetched'): this;
    (event: 'Enabled_Exception'): this;
    (event: 'Syncing_Enabled'): this;
    (event: 'Syncing_Any'): this;
    (event: 'Syncing_Synced'): this;
    (event: 'Syncing_Restart'): this;
    (event: 'Syncing_PreparingList'): this;
    (event: 'Syncing_ListReady'): this;
    (event: 'Syncing_FetchingTasks'): this;
    (event: 'Syncing_TasksFetched'): this;
    (event: 'Syncing_TasksCached'): this;
    (event: 'Syncing_SyncingThreadsToTasks'): this;
    (event: 'Syncing_ThreadsToTasksSynced'): this;
    (event: 'Syncing_SyncingTasksToThreads'): this;
    (event: 'Syncing_TasksToThreadsSynced'): this;
    (event: 'Syncing_SyncingCompletedThreads'): this;
    (event: 'Syncing_CompletedThreadsSynced'): this;
    (event: 'Syncing_SyncingCompletedTasks'): this;
    (event: 'Syncing_CompletedTasksSynced'): this;
    (event: 'Syncing_ThreadsFetched'): this;
    (event: 'Syncing_MsgsFetched'): this;
    (event: 'Syncing_Exception'): this;
    (event: 'Synced_Enabled'): this;
    (event: 'Synced_Syncing'): this;
    (event: 'Synced_Any'): this;
    (event: 'Synced_Restart'): this;
    (event: 'Synced_PreparingList'): this;
    (event: 'Synced_ListReady'): this;
    (event: 'Synced_FetchingTasks'): this;
    (event: 'Synced_TasksFetched'): this;
    (event: 'Synced_TasksCached'): this;
    (event: 'Synced_SyncingThreadsToTasks'): this;
    (event: 'Synced_ThreadsToTasksSynced'): this;
    (event: 'Synced_SyncingTasksToThreads'): this;
    (event: 'Synced_TasksToThreadsSynced'): this;
    (event: 'Synced_SyncingCompletedThreads'): this;
    (event: 'Synced_CompletedThreadsSynced'): this;
    (event: 'Synced_SyncingCompletedTasks'): this;
    (event: 'Synced_CompletedTasksSynced'): this;
    (event: 'Synced_ThreadsFetched'): this;
    (event: 'Synced_MsgsFetched'): this;
    (event: 'Synced_Exception'): this;
    (event: 'Restart_Enabled'): this;
    (event: 'Restart_Syncing'): this;
    (event: 'Restart_Synced'): this;
    (event: 'Restart_Any'): this;
    (event: 'Restart_PreparingList'): this;
    (event: 'Restart_ListReady'): this;
    (event: 'Restart_FetchingTasks'): this;
    (event: 'Restart_TasksFetched'): this;
    (event: 'Restart_TasksCached'): this;
    (event: 'Restart_SyncingThreadsToTasks'): this;
    (event: 'Restart_ThreadsToTasksSynced'): this;
    (event: 'Restart_SyncingTasksToThreads'): this;
    (event: 'Restart_TasksToThreadsSynced'): this;
    (event: 'Restart_SyncingCompletedThreads'): this;
    (event: 'Restart_CompletedThreadsSynced'): this;
    (event: 'Restart_SyncingCompletedTasks'): this;
    (event: 'Restart_CompletedTasksSynced'): this;
    (event: 'Restart_ThreadsFetched'): this;
    (event: 'Restart_MsgsFetched'): this;
    (event: 'Restart_Exception'): this;
    (event: 'PreparingList_Enabled'): this;
    (event: 'PreparingList_Syncing'): this;
    (event: 'PreparingList_Synced'): this;
    (event: 'PreparingList_Restart'): this;
    (event: 'PreparingList_Any'): this;
    (event: 'PreparingList_ListReady'): this;
    (event: 'PreparingList_FetchingTasks'): this;
    (event: 'PreparingList_TasksFetched'): this;
    (event: 'PreparingList_TasksCached'): this;
    (event: 'PreparingList_SyncingThreadsToTasks'): this;
    (event: 'PreparingList_ThreadsToTasksSynced'): this;
    (event: 'PreparingList_SyncingTasksToThreads'): this;
    (event: 'PreparingList_TasksToThreadsSynced'): this;
    (event: 'PreparingList_SyncingCompletedThreads'): this;
    (event: 'PreparingList_CompletedThreadsSynced'): this;
    (event: 'PreparingList_SyncingCompletedTasks'): this;
    (event: 'PreparingList_CompletedTasksSynced'): this;
    (event: 'PreparingList_ThreadsFetched'): this;
    (event: 'PreparingList_MsgsFetched'): this;
    (event: 'PreparingList_Exception'): this;
    (event: 'ListReady_Enabled'): this;
    (event: 'ListReady_Syncing'): this;
    (event: 'ListReady_Synced'): this;
    (event: 'ListReady_Restart'): this;
    (event: 'ListReady_PreparingList'): this;
    (event: 'ListReady_Any'): this;
    (event: 'ListReady_FetchingTasks'): this;
    (event: 'ListReady_TasksFetched'): this;
    (event: 'ListReady_TasksCached'): this;
    (event: 'ListReady_SyncingThreadsToTasks'): this;
    (event: 'ListReady_ThreadsToTasksSynced'): this;
    (event: 'ListReady_SyncingTasksToThreads'): this;
    (event: 'ListReady_TasksToThreadsSynced'): this;
    (event: 'ListReady_SyncingCompletedThreads'): this;
    (event: 'ListReady_CompletedThreadsSynced'): this;
    (event: 'ListReady_SyncingCompletedTasks'): this;
    (event: 'ListReady_CompletedTasksSynced'): this;
    (event: 'ListReady_ThreadsFetched'): this;
    (event: 'ListReady_MsgsFetched'): this;
    (event: 'ListReady_Exception'): this;
    (event: 'FetchingTasks_Enabled'): this;
    (event: 'FetchingTasks_Syncing'): this;
    (event: 'FetchingTasks_Synced'): this;
    (event: 'FetchingTasks_Restart'): this;
    (event: 'FetchingTasks_PreparingList'): this;
    (event: 'FetchingTasks_ListReady'): this;
    (event: 'FetchingTasks_Any'): this;
    (event: 'FetchingTasks_TasksFetched'): this;
    (event: 'FetchingTasks_TasksCached'): this;
    (event: 'FetchingTasks_SyncingThreadsToTasks'): this;
    (event: 'FetchingTasks_ThreadsToTasksSynced'): this;
    (event: 'FetchingTasks_SyncingTasksToThreads'): this;
    (event: 'FetchingTasks_TasksToThreadsSynced'): this;
    (event: 'FetchingTasks_SyncingCompletedThreads'): this;
    (event: 'FetchingTasks_CompletedThreadsSynced'): this;
    (event: 'FetchingTasks_SyncingCompletedTasks'): this;
    (event: 'FetchingTasks_CompletedTasksSynced'): this;
    (event: 'FetchingTasks_ThreadsFetched'): this;
    (event: 'FetchingTasks_MsgsFetched'): this;
    (event: 'FetchingTasks_Exception'): this;
    (event: 'TasksFetched_Enabled'): this;
    (event: 'TasksFetched_Syncing'): this;
    (event: 'TasksFetched_Synced'): this;
    (event: 'TasksFetched_Restart'): this;
    (event: 'TasksFetched_PreparingList'): this;
    (event: 'TasksFetched_ListReady'): this;
    (event: 'TasksFetched_FetchingTasks'): this;
    (event: 'TasksFetched_Any'): this;
    (event: 'TasksFetched_TasksCached'): this;
    (event: 'TasksFetched_SyncingThreadsToTasks'): this;
    (event: 'TasksFetched_ThreadsToTasksSynced'): this;
    (event: 'TasksFetched_SyncingTasksToThreads'): this;
    (event: 'TasksFetched_TasksToThreadsSynced'): this;
    (event: 'TasksFetched_SyncingCompletedThreads'): this;
    (event: 'TasksFetched_CompletedThreadsSynced'): this;
    (event: 'TasksFetched_SyncingCompletedTasks'): this;
    (event: 'TasksFetched_CompletedTasksSynced'): this;
    (event: 'TasksFetched_ThreadsFetched'): this;
    (event: 'TasksFetched_MsgsFetched'): this;
    (event: 'TasksFetched_Exception'): this;
    (event: 'TasksCached_Enabled'): this;
    (event: 'TasksCached_Syncing'): this;
    (event: 'TasksCached_Synced'): this;
    (event: 'TasksCached_Restart'): this;
    (event: 'TasksCached_PreparingList'): this;
    (event: 'TasksCached_ListReady'): this;
    (event: 'TasksCached_FetchingTasks'): this;
    (event: 'TasksCached_TasksFetched'): this;
    (event: 'TasksCached_Any'): this;
    (event: 'TasksCached_SyncingThreadsToTasks'): this;
    (event: 'TasksCached_ThreadsToTasksSynced'): this;
    (event: 'TasksCached_SyncingTasksToThreads'): this;
    (event: 'TasksCached_TasksToThreadsSynced'): this;
    (event: 'TasksCached_SyncingCompletedThreads'): this;
    (event: 'TasksCached_CompletedThreadsSynced'): this;
    (event: 'TasksCached_SyncingCompletedTasks'): this;
    (event: 'TasksCached_CompletedTasksSynced'): this;
    (event: 'TasksCached_ThreadsFetched'): this;
    (event: 'TasksCached_MsgsFetched'): this;
    (event: 'TasksCached_Exception'): this;
    (event: 'SyncingThreadsToTasks_Enabled'): this;
    (event: 'SyncingThreadsToTasks_Syncing'): this;
    (event: 'SyncingThreadsToTasks_Synced'): this;
    (event: 'SyncingThreadsToTasks_Restart'): this;
    (event: 'SyncingThreadsToTasks_PreparingList'): this;
    (event: 'SyncingThreadsToTasks_ListReady'): this;
    (event: 'SyncingThreadsToTasks_FetchingTasks'): this;
    (event: 'SyncingThreadsToTasks_TasksFetched'): this;
    (event: 'SyncingThreadsToTasks_TasksCached'): this;
    (event: 'SyncingThreadsToTasks_Any'): this;
    (event: 'SyncingThreadsToTasks_ThreadsToTasksSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingTasksToThreads'): this;
    (event: 'SyncingThreadsToTasks_TasksToThreadsSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingCompletedThreads'): this;
    (event: 'SyncingThreadsToTasks_CompletedThreadsSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingCompletedTasks'): this;
    (event: 'SyncingThreadsToTasks_CompletedTasksSynced'): this;
    (event: 'SyncingThreadsToTasks_ThreadsFetched'): this;
    (event: 'SyncingThreadsToTasks_MsgsFetched'): this;
    (event: 'SyncingThreadsToTasks_Exception'): this;
    (event: 'ThreadsToTasksSynced_Enabled'): this;
    (event: 'ThreadsToTasksSynced_Syncing'): this;
    (event: 'ThreadsToTasksSynced_Synced'): this;
    (event: 'ThreadsToTasksSynced_Restart'): this;
    (event: 'ThreadsToTasksSynced_PreparingList'): this;
    (event: 'ThreadsToTasksSynced_ListReady'): this;
    (event: 'ThreadsToTasksSynced_FetchingTasks'): this;
    (event: 'ThreadsToTasksSynced_TasksFetched'): this;
    (event: 'ThreadsToTasksSynced_TasksCached'): this;
    (event: 'ThreadsToTasksSynced_SyncingThreadsToTasks'): this;
    (event: 'ThreadsToTasksSynced_Any'): this;
    (event: 'ThreadsToTasksSynced_SyncingTasksToThreads'): this;
    (event: 'ThreadsToTasksSynced_TasksToThreadsSynced'): this;
    (event: 'ThreadsToTasksSynced_SyncingCompletedThreads'): this;
    (event: 'ThreadsToTasksSynced_CompletedThreadsSynced'): this;
    (event: 'ThreadsToTasksSynced_SyncingCompletedTasks'): this;
    (event: 'ThreadsToTasksSynced_CompletedTasksSynced'): this;
    (event: 'ThreadsToTasksSynced_ThreadsFetched'): this;
    (event: 'ThreadsToTasksSynced_MsgsFetched'): this;
    (event: 'ThreadsToTasksSynced_Exception'): this;
    (event: 'SyncingTasksToThreads_Enabled'): this;
    (event: 'SyncingTasksToThreads_Syncing'): this;
    (event: 'SyncingTasksToThreads_Synced'): this;
    (event: 'SyncingTasksToThreads_Restart'): this;
    (event: 'SyncingTasksToThreads_PreparingList'): this;
    (event: 'SyncingTasksToThreads_ListReady'): this;
    (event: 'SyncingTasksToThreads_FetchingTasks'): this;
    (event: 'SyncingTasksToThreads_TasksFetched'): this;
    (event: 'SyncingTasksToThreads_TasksCached'): this;
    (event: 'SyncingTasksToThreads_SyncingThreadsToTasks'): this;
    (event: 'SyncingTasksToThreads_ThreadsToTasksSynced'): this;
    (event: 'SyncingTasksToThreads_Any'): this;
    (event: 'SyncingTasksToThreads_TasksToThreadsSynced'): this;
    (event: 'SyncingTasksToThreads_SyncingCompletedThreads'): this;
    (event: 'SyncingTasksToThreads_CompletedThreadsSynced'): this;
    (event: 'SyncingTasksToThreads_SyncingCompletedTasks'): this;
    (event: 'SyncingTasksToThreads_CompletedTasksSynced'): this;
    (event: 'SyncingTasksToThreads_ThreadsFetched'): this;
    (event: 'SyncingTasksToThreads_MsgsFetched'): this;
    (event: 'SyncingTasksToThreads_Exception'): this;
    (event: 'TasksToThreadsSynced_Enabled'): this;
    (event: 'TasksToThreadsSynced_Syncing'): this;
    (event: 'TasksToThreadsSynced_Synced'): this;
    (event: 'TasksToThreadsSynced_Restart'): this;
    (event: 'TasksToThreadsSynced_PreparingList'): this;
    (event: 'TasksToThreadsSynced_ListReady'): this;
    (event: 'TasksToThreadsSynced_FetchingTasks'): this;
    (event: 'TasksToThreadsSynced_TasksFetched'): this;
    (event: 'TasksToThreadsSynced_TasksCached'): this;
    (event: 'TasksToThreadsSynced_SyncingThreadsToTasks'): this;
    (event: 'TasksToThreadsSynced_ThreadsToTasksSynced'): this;
    (event: 'TasksToThreadsSynced_SyncingTasksToThreads'): this;
    (event: 'TasksToThreadsSynced_Any'): this;
    (event: 'TasksToThreadsSynced_SyncingCompletedThreads'): this;
    (event: 'TasksToThreadsSynced_CompletedThreadsSynced'): this;
    (event: 'TasksToThreadsSynced_SyncingCompletedTasks'): this;
    (event: 'TasksToThreadsSynced_CompletedTasksSynced'): this;
    (event: 'TasksToThreadsSynced_ThreadsFetched'): this;
    (event: 'TasksToThreadsSynced_MsgsFetched'): this;
    (event: 'TasksToThreadsSynced_Exception'): this;
    (event: 'SyncingCompletedThreads_Enabled'): this;
    (event: 'SyncingCompletedThreads_Syncing'): this;
    (event: 'SyncingCompletedThreads_Synced'): this;
    (event: 'SyncingCompletedThreads_Restart'): this;
    (event: 'SyncingCompletedThreads_PreparingList'): this;
    (event: 'SyncingCompletedThreads_ListReady'): this;
    (event: 'SyncingCompletedThreads_FetchingTasks'): this;
    (event: 'SyncingCompletedThreads_TasksFetched'): this;
    (event: 'SyncingCompletedThreads_TasksCached'): this;
    (event: 'SyncingCompletedThreads_SyncingThreadsToTasks'): this;
    (event: 'SyncingCompletedThreads_ThreadsToTasksSynced'): this;
    (event: 'SyncingCompletedThreads_SyncingTasksToThreads'): this;
    (event: 'SyncingCompletedThreads_TasksToThreadsSynced'): this;
    (event: 'SyncingCompletedThreads_Any'): this;
    (event: 'SyncingCompletedThreads_CompletedThreadsSynced'): this;
    (event: 'SyncingCompletedThreads_SyncingCompletedTasks'): this;
    (event: 'SyncingCompletedThreads_CompletedTasksSynced'): this;
    (event: 'SyncingCompletedThreads_ThreadsFetched'): this;
    (event: 'SyncingCompletedThreads_MsgsFetched'): this;
    (event: 'SyncingCompletedThreads_Exception'): this;
    (event: 'CompletedThreadsSynced_Enabled'): this;
    (event: 'CompletedThreadsSynced_Syncing'): this;
    (event: 'CompletedThreadsSynced_Synced'): this;
    (event: 'CompletedThreadsSynced_Restart'): this;
    (event: 'CompletedThreadsSynced_PreparingList'): this;
    (event: 'CompletedThreadsSynced_ListReady'): this;
    (event: 'CompletedThreadsSynced_FetchingTasks'): this;
    (event: 'CompletedThreadsSynced_TasksFetched'): this;
    (event: 'CompletedThreadsSynced_TasksCached'): this;
    (event: 'CompletedThreadsSynced_SyncingThreadsToTasks'): this;
    (event: 'CompletedThreadsSynced_ThreadsToTasksSynced'): this;
    (event: 'CompletedThreadsSynced_SyncingTasksToThreads'): this;
    (event: 'CompletedThreadsSynced_TasksToThreadsSynced'): this;
    (event: 'CompletedThreadsSynced_SyncingCompletedThreads'): this;
    (event: 'CompletedThreadsSynced_Any'): this;
    (event: 'CompletedThreadsSynced_SyncingCompletedTasks'): this;
    (event: 'CompletedThreadsSynced_CompletedTasksSynced'): this;
    (event: 'CompletedThreadsSynced_ThreadsFetched'): this;
    (event: 'CompletedThreadsSynced_MsgsFetched'): this;
    (event: 'CompletedThreadsSynced_Exception'): this;
    (event: 'SyncingCompletedTasks_Enabled'): this;
    (event: 'SyncingCompletedTasks_Syncing'): this;
    (event: 'SyncingCompletedTasks_Synced'): this;
    (event: 'SyncingCompletedTasks_Restart'): this;
    (event: 'SyncingCompletedTasks_PreparingList'): this;
    (event: 'SyncingCompletedTasks_ListReady'): this;
    (event: 'SyncingCompletedTasks_FetchingTasks'): this;
    (event: 'SyncingCompletedTasks_TasksFetched'): this;
    (event: 'SyncingCompletedTasks_TasksCached'): this;
    (event: 'SyncingCompletedTasks_SyncingThreadsToTasks'): this;
    (event: 'SyncingCompletedTasks_ThreadsToTasksSynced'): this;
    (event: 'SyncingCompletedTasks_SyncingTasksToThreads'): this;
    (event: 'SyncingCompletedTasks_TasksToThreadsSynced'): this;
    (event: 'SyncingCompletedTasks_SyncingCompletedThreads'): this;
    (event: 'SyncingCompletedTasks_CompletedThreadsSynced'): this;
    (event: 'SyncingCompletedTasks_Any'): this;
    (event: 'SyncingCompletedTasks_CompletedTasksSynced'): this;
    (event: 'SyncingCompletedTasks_ThreadsFetched'): this;
    (event: 'SyncingCompletedTasks_MsgsFetched'): this;
    (event: 'SyncingCompletedTasks_Exception'): this;
    (event: 'CompletedTasksSynced_Enabled'): this;
    (event: 'CompletedTasksSynced_Syncing'): this;
    (event: 'CompletedTasksSynced_Synced'): this;
    (event: 'CompletedTasksSynced_Restart'): this;
    (event: 'CompletedTasksSynced_PreparingList'): this;
    (event: 'CompletedTasksSynced_ListReady'): this;
    (event: 'CompletedTasksSynced_FetchingTasks'): this;
    (event: 'CompletedTasksSynced_TasksFetched'): this;
    (event: 'CompletedTasksSynced_TasksCached'): this;
    (event: 'CompletedTasksSynced_SyncingThreadsToTasks'): this;
    (event: 'CompletedTasksSynced_ThreadsToTasksSynced'): this;
    (event: 'CompletedTasksSynced_SyncingTasksToThreads'): this;
    (event: 'CompletedTasksSynced_TasksToThreadsSynced'): this;
    (event: 'CompletedTasksSynced_SyncingCompletedThreads'): this;
    (event: 'CompletedTasksSynced_CompletedThreadsSynced'): this;
    (event: 'CompletedTasksSynced_SyncingCompletedTasks'): this;
    (event: 'CompletedTasksSynced_Any'): this;
    (event: 'CompletedTasksSynced_ThreadsFetched'): this;
    (event: 'CompletedTasksSynced_MsgsFetched'): this;
    (event: 'CompletedTasksSynced_Exception'): this;
    (event: 'ThreadsFetched_Enabled'): this;
    (event: 'ThreadsFetched_Syncing'): this;
    (event: 'ThreadsFetched_Synced'): this;
    (event: 'ThreadsFetched_Restart'): this;
    (event: 'ThreadsFetched_PreparingList'): this;
    (event: 'ThreadsFetched_ListReady'): this;
    (event: 'ThreadsFetched_FetchingTasks'): this;
    (event: 'ThreadsFetched_TasksFetched'): this;
    (event: 'ThreadsFetched_TasksCached'): this;
    (event: 'ThreadsFetched_SyncingThreadsToTasks'): this;
    (event: 'ThreadsFetched_ThreadsToTasksSynced'): this;
    (event: 'ThreadsFetched_SyncingTasksToThreads'): this;
    (event: 'ThreadsFetched_TasksToThreadsSynced'): this;
    (event: 'ThreadsFetched_SyncingCompletedThreads'): this;
    (event: 'ThreadsFetched_CompletedThreadsSynced'): this;
    (event: 'ThreadsFetched_SyncingCompletedTasks'): this;
    (event: 'ThreadsFetched_CompletedTasksSynced'): this;
    (event: 'ThreadsFetched_Any'): this;
    (event: 'ThreadsFetched_MsgsFetched'): this;
    (event: 'ThreadsFetched_Exception'): this;
    (event: 'MsgsFetched_Enabled'): this;
    (event: 'MsgsFetched_Syncing'): this;
    (event: 'MsgsFetched_Synced'): this;
    (event: 'MsgsFetched_Restart'): this;
    (event: 'MsgsFetched_PreparingList'): this;
    (event: 'MsgsFetched_ListReady'): this;
    (event: 'MsgsFetched_FetchingTasks'): this;
    (event: 'MsgsFetched_TasksFetched'): this;
    (event: 'MsgsFetched_TasksCached'): this;
    (event: 'MsgsFetched_SyncingThreadsToTasks'): this;
    (event: 'MsgsFetched_ThreadsToTasksSynced'): this;
    (event: 'MsgsFetched_SyncingTasksToThreads'): this;
    (event: 'MsgsFetched_TasksToThreadsSynced'): this;
    (event: 'MsgsFetched_SyncingCompletedThreads'): this;
    (event: 'MsgsFetched_CompletedThreadsSynced'): this;
    (event: 'MsgsFetched_SyncingCompletedTasks'): this;
    (event: 'MsgsFetched_CompletedTasksSynced'): this;
    (event: 'MsgsFetched_ThreadsFetched'): this;
    (event: 'MsgsFetched_Any'): this;
    (event: 'MsgsFetched_Exception'): this;
    (event: 'Exception_Enabled'): this;
    (event: 'Exception_Syncing'): this;
    (event: 'Exception_Synced'): this;
    (event: 'Exception_Restart'): this;
    (event: 'Exception_PreparingList'): this;
    (event: 'Exception_ListReady'): this;
    (event: 'Exception_FetchingTasks'): this;
    (event: 'Exception_TasksFetched'): this;
    (event: 'Exception_TasksCached'): this;
    (event: 'Exception_SyncingThreadsToTasks'): this;
    (event: 'Exception_ThreadsToTasksSynced'): this;
    (event: 'Exception_SyncingTasksToThreads'): this;
    (event: 'Exception_TasksToThreadsSynced'): this;
    (event: 'Exception_SyncingCompletedThreads'): this;
    (event: 'Exception_CompletedThreadsSynced'): this;
    (event: 'Exception_SyncingCompletedTasks'): this;
    (event: 'Exception_CompletedTasksSynced'): this;
    (event: 'Exception_ThreadsFetched'): this;
    (event: 'Exception_MsgsFetched'): this;
}

export interface IEmit {
    
    // Enabled
    (event: 'Enabled_enter' /*, param1, param2 */): this;
    (event: 'Enabled_state' /*, param1, param2 */): this;
    // Syncing
    (event: 'Syncing_enter' /*, param1, param2 */): this;
    (event: 'Syncing_state' /*, param1, param2 */): this;
    // Synced
    (event: 'Synced_enter' /*, param1, param2 */): this;
    (event: 'Synced_state' /*, param1, param2 */): this;
    // Restart
    (event: 'Restart_enter' /*, param1, param2 */): this;
    (event: 'Restart_state' /*, param1, param2 */): this;
    // PreparingList
    (event: 'PreparingList_enter' /*, param1, param2 */): this;
    (event: 'PreparingList_state' /*, param1, param2 */): this;
    // ListReady
    (event: 'ListReady_enter' /*, param1, param2 */): this;
    (event: 'ListReady_state' /*, param1, param2 */): this;
    // FetchingTasks
    (event: 'FetchingTasks_enter' /*, param1, param2 */): this;
    (event: 'FetchingTasks_state' /*, param1, param2 */): this;
    // TasksFetched
    (event: 'TasksFetched_enter' /*, param1, param2 */): this;
    (event: 'TasksFetched_state' /*, param1, param2 */): this;
    // TasksCached
    (event: 'TasksCached_enter' /*, param1, param2 */): this;
    (event: 'TasksCached_state' /*, param1, param2 */): this;
    // SyncingThreadsToTasks
    (event: 'SyncingThreadsToTasks_enter' /*, param1, param2 */): this;
    (event: 'SyncingThreadsToTasks_state' /*, param1, param2 */): this;
    // ThreadsToTasksSynced
    (event: 'ThreadsToTasksSynced_enter' /*, param1, param2 */): this;
    (event: 'ThreadsToTasksSynced_state' /*, param1, param2 */): this;
    // SyncingTasksToThreads
    (event: 'SyncingTasksToThreads_enter' /*, param1, param2 */): this;
    (event: 'SyncingTasksToThreads_state' /*, param1, param2 */): this;
    // TasksToThreadsSynced
    (event: 'TasksToThreadsSynced_enter' /*, param1, param2 */): this;
    (event: 'TasksToThreadsSynced_state' /*, param1, param2 */): this;
    // SyncingCompletedThreads
    (event: 'SyncingCompletedThreads_enter' /*, param1, param2 */): this;
    (event: 'SyncingCompletedThreads_state' /*, param1, param2 */): this;
    // CompletedThreadsSynced
    (event: 'CompletedThreadsSynced_enter' /*, param1, param2 */): this;
    (event: 'CompletedThreadsSynced_state' /*, param1, param2 */): this;
    // SyncingCompletedTasks
    (event: 'SyncingCompletedTasks_enter' /*, param1, param2 */): this;
    (event: 'SyncingCompletedTasks_state' /*, param1, param2 */): this;
    // CompletedTasksSynced
    (event: 'CompletedTasksSynced_enter' /*, param1, param2 */): this;
    (event: 'CompletedTasksSynced_state' /*, param1, param2 */): this;
    // ThreadsFetched
    (event: 'ThreadsFetched_enter' /*, param1, param2 */): this;
    (event: 'ThreadsFetched_state' /*, param1, param2 */): this;
    // MsgsFetched
    (event: 'MsgsFetched_enter' /*, param1, param2 */): this;
    (event: 'MsgsFetched_state' /*, param1, param2 */): this;


    // Non-params events
    (event: 'Enabled_exit'): this;
    (event: 'Enabled_end'): this;
    (event: 'Syncing_exit'): this;
    (event: 'Syncing_end'): this;
    (event: 'Synced_exit'): this;
    (event: 'Synced_end'): this;
    (event: 'Restart_exit'): this;
    (event: 'Restart_end'): this;
    (event: 'PreparingList_exit'): this;
    (event: 'PreparingList_end'): this;
    (event: 'ListReady_exit'): this;
    (event: 'ListReady_end'): this;
    (event: 'FetchingTasks_exit'): this;
    (event: 'FetchingTasks_end'): this;
    (event: 'TasksFetched_exit'): this;
    (event: 'TasksFetched_end'): this;
    (event: 'TasksCached_exit'): this;
    (event: 'TasksCached_end'): this;
    (event: 'SyncingThreadsToTasks_exit'): this;
    (event: 'SyncingThreadsToTasks_end'): this;
    (event: 'ThreadsToTasksSynced_exit'): this;
    (event: 'ThreadsToTasksSynced_end'): this;
    (event: 'SyncingTasksToThreads_exit'): this;
    (event: 'SyncingTasksToThreads_end'): this;
    (event: 'TasksToThreadsSynced_exit'): this;
    (event: 'TasksToThreadsSynced_end'): this;
    (event: 'SyncingCompletedThreads_exit'): this;
    (event: 'SyncingCompletedThreads_end'): this;
    (event: 'CompletedThreadsSynced_exit'): this;
    (event: 'CompletedThreadsSynced_end'): this;
    (event: 'SyncingCompletedTasks_exit'): this;
    (event: 'SyncingCompletedTasks_end'): this;
    (event: 'CompletedTasksSynced_exit'): this;
    (event: 'CompletedTasksSynced_end'): this;
    (event: 'ThreadsFetched_exit'): this;
    (event: 'ThreadsFetched_end'): this;
    (event: 'MsgsFetched_exit'): this;
    (event: 'MsgsFetched_end'): this;

    // Transitions

    (event: 'Enabled_Any'): this;
    (event: 'Enabled_Syncing'): this;
    (event: 'Enabled_Synced'): this;
    (event: 'Enabled_Restart'): this;
    (event: 'Enabled_PreparingList'): this;
    (event: 'Enabled_ListReady'): this;
    (event: 'Enabled_FetchingTasks'): this;
    (event: 'Enabled_TasksFetched'): this;
    (event: 'Enabled_TasksCached'): this;
    (event: 'Enabled_SyncingThreadsToTasks'): this;
    (event: 'Enabled_ThreadsToTasksSynced'): this;
    (event: 'Enabled_SyncingTasksToThreads'): this;
    (event: 'Enabled_TasksToThreadsSynced'): this;
    (event: 'Enabled_SyncingCompletedThreads'): this;
    (event: 'Enabled_CompletedThreadsSynced'): this;
    (event: 'Enabled_SyncingCompletedTasks'): this;
    (event: 'Enabled_CompletedTasksSynced'): this;
    (event: 'Enabled_ThreadsFetched'): this;
    (event: 'Enabled_MsgsFetched'): this;
    (event: 'Enabled_Exception'): this;
    (event: 'Syncing_Enabled'): this;
    (event: 'Syncing_Any'): this;
    (event: 'Syncing_Synced'): this;
    (event: 'Syncing_Restart'): this;
    (event: 'Syncing_PreparingList'): this;
    (event: 'Syncing_ListReady'): this;
    (event: 'Syncing_FetchingTasks'): this;
    (event: 'Syncing_TasksFetched'): this;
    (event: 'Syncing_TasksCached'): this;
    (event: 'Syncing_SyncingThreadsToTasks'): this;
    (event: 'Syncing_ThreadsToTasksSynced'): this;
    (event: 'Syncing_SyncingTasksToThreads'): this;
    (event: 'Syncing_TasksToThreadsSynced'): this;
    (event: 'Syncing_SyncingCompletedThreads'): this;
    (event: 'Syncing_CompletedThreadsSynced'): this;
    (event: 'Syncing_SyncingCompletedTasks'): this;
    (event: 'Syncing_CompletedTasksSynced'): this;
    (event: 'Syncing_ThreadsFetched'): this;
    (event: 'Syncing_MsgsFetched'): this;
    (event: 'Syncing_Exception'): this;
    (event: 'Synced_Enabled'): this;
    (event: 'Synced_Syncing'): this;
    (event: 'Synced_Any'): this;
    (event: 'Synced_Restart'): this;
    (event: 'Synced_PreparingList'): this;
    (event: 'Synced_ListReady'): this;
    (event: 'Synced_FetchingTasks'): this;
    (event: 'Synced_TasksFetched'): this;
    (event: 'Synced_TasksCached'): this;
    (event: 'Synced_SyncingThreadsToTasks'): this;
    (event: 'Synced_ThreadsToTasksSynced'): this;
    (event: 'Synced_SyncingTasksToThreads'): this;
    (event: 'Synced_TasksToThreadsSynced'): this;
    (event: 'Synced_SyncingCompletedThreads'): this;
    (event: 'Synced_CompletedThreadsSynced'): this;
    (event: 'Synced_SyncingCompletedTasks'): this;
    (event: 'Synced_CompletedTasksSynced'): this;
    (event: 'Synced_ThreadsFetched'): this;
    (event: 'Synced_MsgsFetched'): this;
    (event: 'Synced_Exception'): this;
    (event: 'Restart_Enabled'): this;
    (event: 'Restart_Syncing'): this;
    (event: 'Restart_Synced'): this;
    (event: 'Restart_Any'): this;
    (event: 'Restart_PreparingList'): this;
    (event: 'Restart_ListReady'): this;
    (event: 'Restart_FetchingTasks'): this;
    (event: 'Restart_TasksFetched'): this;
    (event: 'Restart_TasksCached'): this;
    (event: 'Restart_SyncingThreadsToTasks'): this;
    (event: 'Restart_ThreadsToTasksSynced'): this;
    (event: 'Restart_SyncingTasksToThreads'): this;
    (event: 'Restart_TasksToThreadsSynced'): this;
    (event: 'Restart_SyncingCompletedThreads'): this;
    (event: 'Restart_CompletedThreadsSynced'): this;
    (event: 'Restart_SyncingCompletedTasks'): this;
    (event: 'Restart_CompletedTasksSynced'): this;
    (event: 'Restart_ThreadsFetched'): this;
    (event: 'Restart_MsgsFetched'): this;
    (event: 'Restart_Exception'): this;
    (event: 'PreparingList_Enabled'): this;
    (event: 'PreparingList_Syncing'): this;
    (event: 'PreparingList_Synced'): this;
    (event: 'PreparingList_Restart'): this;
    (event: 'PreparingList_Any'): this;
    (event: 'PreparingList_ListReady'): this;
    (event: 'PreparingList_FetchingTasks'): this;
    (event: 'PreparingList_TasksFetched'): this;
    (event: 'PreparingList_TasksCached'): this;
    (event: 'PreparingList_SyncingThreadsToTasks'): this;
    (event: 'PreparingList_ThreadsToTasksSynced'): this;
    (event: 'PreparingList_SyncingTasksToThreads'): this;
    (event: 'PreparingList_TasksToThreadsSynced'): this;
    (event: 'PreparingList_SyncingCompletedThreads'): this;
    (event: 'PreparingList_CompletedThreadsSynced'): this;
    (event: 'PreparingList_SyncingCompletedTasks'): this;
    (event: 'PreparingList_CompletedTasksSynced'): this;
    (event: 'PreparingList_ThreadsFetched'): this;
    (event: 'PreparingList_MsgsFetched'): this;
    (event: 'PreparingList_Exception'): this;
    (event: 'ListReady_Enabled'): this;
    (event: 'ListReady_Syncing'): this;
    (event: 'ListReady_Synced'): this;
    (event: 'ListReady_Restart'): this;
    (event: 'ListReady_PreparingList'): this;
    (event: 'ListReady_Any'): this;
    (event: 'ListReady_FetchingTasks'): this;
    (event: 'ListReady_TasksFetched'): this;
    (event: 'ListReady_TasksCached'): this;
    (event: 'ListReady_SyncingThreadsToTasks'): this;
    (event: 'ListReady_ThreadsToTasksSynced'): this;
    (event: 'ListReady_SyncingTasksToThreads'): this;
    (event: 'ListReady_TasksToThreadsSynced'): this;
    (event: 'ListReady_SyncingCompletedThreads'): this;
    (event: 'ListReady_CompletedThreadsSynced'): this;
    (event: 'ListReady_SyncingCompletedTasks'): this;
    (event: 'ListReady_CompletedTasksSynced'): this;
    (event: 'ListReady_ThreadsFetched'): this;
    (event: 'ListReady_MsgsFetched'): this;
    (event: 'ListReady_Exception'): this;
    (event: 'FetchingTasks_Enabled'): this;
    (event: 'FetchingTasks_Syncing'): this;
    (event: 'FetchingTasks_Synced'): this;
    (event: 'FetchingTasks_Restart'): this;
    (event: 'FetchingTasks_PreparingList'): this;
    (event: 'FetchingTasks_ListReady'): this;
    (event: 'FetchingTasks_Any'): this;
    (event: 'FetchingTasks_TasksFetched'): this;
    (event: 'FetchingTasks_TasksCached'): this;
    (event: 'FetchingTasks_SyncingThreadsToTasks'): this;
    (event: 'FetchingTasks_ThreadsToTasksSynced'): this;
    (event: 'FetchingTasks_SyncingTasksToThreads'): this;
    (event: 'FetchingTasks_TasksToThreadsSynced'): this;
    (event: 'FetchingTasks_SyncingCompletedThreads'): this;
    (event: 'FetchingTasks_CompletedThreadsSynced'): this;
    (event: 'FetchingTasks_SyncingCompletedTasks'): this;
    (event: 'FetchingTasks_CompletedTasksSynced'): this;
    (event: 'FetchingTasks_ThreadsFetched'): this;
    (event: 'FetchingTasks_MsgsFetched'): this;
    (event: 'FetchingTasks_Exception'): this;
    (event: 'TasksFetched_Enabled'): this;
    (event: 'TasksFetched_Syncing'): this;
    (event: 'TasksFetched_Synced'): this;
    (event: 'TasksFetched_Restart'): this;
    (event: 'TasksFetched_PreparingList'): this;
    (event: 'TasksFetched_ListReady'): this;
    (event: 'TasksFetched_FetchingTasks'): this;
    (event: 'TasksFetched_Any'): this;
    (event: 'TasksFetched_TasksCached'): this;
    (event: 'TasksFetched_SyncingThreadsToTasks'): this;
    (event: 'TasksFetched_ThreadsToTasksSynced'): this;
    (event: 'TasksFetched_SyncingTasksToThreads'): this;
    (event: 'TasksFetched_TasksToThreadsSynced'): this;
    (event: 'TasksFetched_SyncingCompletedThreads'): this;
    (event: 'TasksFetched_CompletedThreadsSynced'): this;
    (event: 'TasksFetched_SyncingCompletedTasks'): this;
    (event: 'TasksFetched_CompletedTasksSynced'): this;
    (event: 'TasksFetched_ThreadsFetched'): this;
    (event: 'TasksFetched_MsgsFetched'): this;
    (event: 'TasksFetched_Exception'): this;
    (event: 'TasksCached_Enabled'): this;
    (event: 'TasksCached_Syncing'): this;
    (event: 'TasksCached_Synced'): this;
    (event: 'TasksCached_Restart'): this;
    (event: 'TasksCached_PreparingList'): this;
    (event: 'TasksCached_ListReady'): this;
    (event: 'TasksCached_FetchingTasks'): this;
    (event: 'TasksCached_TasksFetched'): this;
    (event: 'TasksCached_Any'): this;
    (event: 'TasksCached_SyncingThreadsToTasks'): this;
    (event: 'TasksCached_ThreadsToTasksSynced'): this;
    (event: 'TasksCached_SyncingTasksToThreads'): this;
    (event: 'TasksCached_TasksToThreadsSynced'): this;
    (event: 'TasksCached_SyncingCompletedThreads'): this;
    (event: 'TasksCached_CompletedThreadsSynced'): this;
    (event: 'TasksCached_SyncingCompletedTasks'): this;
    (event: 'TasksCached_CompletedTasksSynced'): this;
    (event: 'TasksCached_ThreadsFetched'): this;
    (event: 'TasksCached_MsgsFetched'): this;
    (event: 'TasksCached_Exception'): this;
    (event: 'SyncingThreadsToTasks_Enabled'): this;
    (event: 'SyncingThreadsToTasks_Syncing'): this;
    (event: 'SyncingThreadsToTasks_Synced'): this;
    (event: 'SyncingThreadsToTasks_Restart'): this;
    (event: 'SyncingThreadsToTasks_PreparingList'): this;
    (event: 'SyncingThreadsToTasks_ListReady'): this;
    (event: 'SyncingThreadsToTasks_FetchingTasks'): this;
    (event: 'SyncingThreadsToTasks_TasksFetched'): this;
    (event: 'SyncingThreadsToTasks_TasksCached'): this;
    (event: 'SyncingThreadsToTasks_Any'): this;
    (event: 'SyncingThreadsToTasks_ThreadsToTasksSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingTasksToThreads'): this;
    (event: 'SyncingThreadsToTasks_TasksToThreadsSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingCompletedThreads'): this;
    (event: 'SyncingThreadsToTasks_CompletedThreadsSynced'): this;
    (event: 'SyncingThreadsToTasks_SyncingCompletedTasks'): this;
    (event: 'SyncingThreadsToTasks_CompletedTasksSynced'): this;
    (event: 'SyncingThreadsToTasks_ThreadsFetched'): this;
    (event: 'SyncingThreadsToTasks_MsgsFetched'): this;
    (event: 'SyncingThreadsToTasks_Exception'): this;
    (event: 'ThreadsToTasksSynced_Enabled'): this;
    (event: 'ThreadsToTasksSynced_Syncing'): this;
    (event: 'ThreadsToTasksSynced_Synced'): this;
    (event: 'ThreadsToTasksSynced_Restart'): this;
    (event: 'ThreadsToTasksSynced_PreparingList'): this;
    (event: 'ThreadsToTasksSynced_ListReady'): this;
    (event: 'ThreadsToTasksSynced_FetchingTasks'): this;
    (event: 'ThreadsToTasksSynced_TasksFetched'): this;
    (event: 'ThreadsToTasksSynced_TasksCached'): this;
    (event: 'ThreadsToTasksSynced_SyncingThreadsToTasks'): this;
    (event: 'ThreadsToTasksSynced_Any'): this;
    (event: 'ThreadsToTasksSynced_SyncingTasksToThreads'): this;
    (event: 'ThreadsToTasksSynced_TasksToThreadsSynced'): this;
    (event: 'ThreadsToTasksSynced_SyncingCompletedThreads'): this;
    (event: 'ThreadsToTasksSynced_CompletedThreadsSynced'): this;
    (event: 'ThreadsToTasksSynced_SyncingCompletedTasks'): this;
    (event: 'ThreadsToTasksSynced_CompletedTasksSynced'): this;
    (event: 'ThreadsToTasksSynced_ThreadsFetched'): this;
    (event: 'ThreadsToTasksSynced_MsgsFetched'): this;
    (event: 'ThreadsToTasksSynced_Exception'): this;
    (event: 'SyncingTasksToThreads_Enabled'): this;
    (event: 'SyncingTasksToThreads_Syncing'): this;
    (event: 'SyncingTasksToThreads_Synced'): this;
    (event: 'SyncingTasksToThreads_Restart'): this;
    (event: 'SyncingTasksToThreads_PreparingList'): this;
    (event: 'SyncingTasksToThreads_ListReady'): this;
    (event: 'SyncingTasksToThreads_FetchingTasks'): this;
    (event: 'SyncingTasksToThreads_TasksFetched'): this;
    (event: 'SyncingTasksToThreads_TasksCached'): this;
    (event: 'SyncingTasksToThreads_SyncingThreadsToTasks'): this;
    (event: 'SyncingTasksToThreads_ThreadsToTasksSynced'): this;
    (event: 'SyncingTasksToThreads_Any'): this;
    (event: 'SyncingTasksToThreads_TasksToThreadsSynced'): this;
    (event: 'SyncingTasksToThreads_SyncingCompletedThreads'): this;
    (event: 'SyncingTasksToThreads_CompletedThreadsSynced'): this;
    (event: 'SyncingTasksToThreads_SyncingCompletedTasks'): this;
    (event: 'SyncingTasksToThreads_CompletedTasksSynced'): this;
    (event: 'SyncingTasksToThreads_ThreadsFetched'): this;
    (event: 'SyncingTasksToThreads_MsgsFetched'): this;
    (event: 'SyncingTasksToThreads_Exception'): this;
    (event: 'TasksToThreadsSynced_Enabled'): this;
    (event: 'TasksToThreadsSynced_Syncing'): this;
    (event: 'TasksToThreadsSynced_Synced'): this;
    (event: 'TasksToThreadsSynced_Restart'): this;
    (event: 'TasksToThreadsSynced_PreparingList'): this;
    (event: 'TasksToThreadsSynced_ListReady'): this;
    (event: 'TasksToThreadsSynced_FetchingTasks'): this;
    (event: 'TasksToThreadsSynced_TasksFetched'): this;
    (event: 'TasksToThreadsSynced_TasksCached'): this;
    (event: 'TasksToThreadsSynced_SyncingThreadsToTasks'): this;
    (event: 'TasksToThreadsSynced_ThreadsToTasksSynced'): this;
    (event: 'TasksToThreadsSynced_SyncingTasksToThreads'): this;
    (event: 'TasksToThreadsSynced_Any'): this;
    (event: 'TasksToThreadsSynced_SyncingCompletedThreads'): this;
    (event: 'TasksToThreadsSynced_CompletedThreadsSynced'): this;
    (event: 'TasksToThreadsSynced_SyncingCompletedTasks'): this;
    (event: 'TasksToThreadsSynced_CompletedTasksSynced'): this;
    (event: 'TasksToThreadsSynced_ThreadsFetched'): this;
    (event: 'TasksToThreadsSynced_MsgsFetched'): this;
    (event: 'TasksToThreadsSynced_Exception'): this;
    (event: 'SyncingCompletedThreads_Enabled'): this;
    (event: 'SyncingCompletedThreads_Syncing'): this;
    (event: 'SyncingCompletedThreads_Synced'): this;
    (event: 'SyncingCompletedThreads_Restart'): this;
    (event: 'SyncingCompletedThreads_PreparingList'): this;
    (event: 'SyncingCompletedThreads_ListReady'): this;
    (event: 'SyncingCompletedThreads_FetchingTasks'): this;
    (event: 'SyncingCompletedThreads_TasksFetched'): this;
    (event: 'SyncingCompletedThreads_TasksCached'): this;
    (event: 'SyncingCompletedThreads_SyncingThreadsToTasks'): this;
    (event: 'SyncingCompletedThreads_ThreadsToTasksSynced'): this;
    (event: 'SyncingCompletedThreads_SyncingTasksToThreads'): this;
    (event: 'SyncingCompletedThreads_TasksToThreadsSynced'): this;
    (event: 'SyncingCompletedThreads_Any'): this;
    (event: 'SyncingCompletedThreads_CompletedThreadsSynced'): this;
    (event: 'SyncingCompletedThreads_SyncingCompletedTasks'): this;
    (event: 'SyncingCompletedThreads_CompletedTasksSynced'): this;
    (event: 'SyncingCompletedThreads_ThreadsFetched'): this;
    (event: 'SyncingCompletedThreads_MsgsFetched'): this;
    (event: 'SyncingCompletedThreads_Exception'): this;
    (event: 'CompletedThreadsSynced_Enabled'): this;
    (event: 'CompletedThreadsSynced_Syncing'): this;
    (event: 'CompletedThreadsSynced_Synced'): this;
    (event: 'CompletedThreadsSynced_Restart'): this;
    (event: 'CompletedThreadsSynced_PreparingList'): this;
    (event: 'CompletedThreadsSynced_ListReady'): this;
    (event: 'CompletedThreadsSynced_FetchingTasks'): this;
    (event: 'CompletedThreadsSynced_TasksFetched'): this;
    (event: 'CompletedThreadsSynced_TasksCached'): this;
    (event: 'CompletedThreadsSynced_SyncingThreadsToTasks'): this;
    (event: 'CompletedThreadsSynced_ThreadsToTasksSynced'): this;
    (event: 'CompletedThreadsSynced_SyncingTasksToThreads'): this;
    (event: 'CompletedThreadsSynced_TasksToThreadsSynced'): this;
    (event: 'CompletedThreadsSynced_SyncingCompletedThreads'): this;
    (event: 'CompletedThreadsSynced_Any'): this;
    (event: 'CompletedThreadsSynced_SyncingCompletedTasks'): this;
    (event: 'CompletedThreadsSynced_CompletedTasksSynced'): this;
    (event: 'CompletedThreadsSynced_ThreadsFetched'): this;
    (event: 'CompletedThreadsSynced_MsgsFetched'): this;
    (event: 'CompletedThreadsSynced_Exception'): this;
    (event: 'SyncingCompletedTasks_Enabled'): this;
    (event: 'SyncingCompletedTasks_Syncing'): this;
    (event: 'SyncingCompletedTasks_Synced'): this;
    (event: 'SyncingCompletedTasks_Restart'): this;
    (event: 'SyncingCompletedTasks_PreparingList'): this;
    (event: 'SyncingCompletedTasks_ListReady'): this;
    (event: 'SyncingCompletedTasks_FetchingTasks'): this;
    (event: 'SyncingCompletedTasks_TasksFetched'): this;
    (event: 'SyncingCompletedTasks_TasksCached'): this;
    (event: 'SyncingCompletedTasks_SyncingThreadsToTasks'): this;
    (event: 'SyncingCompletedTasks_ThreadsToTasksSynced'): this;
    (event: 'SyncingCompletedTasks_SyncingTasksToThreads'): this;
    (event: 'SyncingCompletedTasks_TasksToThreadsSynced'): this;
    (event: 'SyncingCompletedTasks_SyncingCompletedThreads'): this;
    (event: 'SyncingCompletedTasks_CompletedThreadsSynced'): this;
    (event: 'SyncingCompletedTasks_Any'): this;
    (event: 'SyncingCompletedTasks_CompletedTasksSynced'): this;
    (event: 'SyncingCompletedTasks_ThreadsFetched'): this;
    (event: 'SyncingCompletedTasks_MsgsFetched'): this;
    (event: 'SyncingCompletedTasks_Exception'): this;
    (event: 'CompletedTasksSynced_Enabled'): this;
    (event: 'CompletedTasksSynced_Syncing'): this;
    (event: 'CompletedTasksSynced_Synced'): this;
    (event: 'CompletedTasksSynced_Restart'): this;
    (event: 'CompletedTasksSynced_PreparingList'): this;
    (event: 'CompletedTasksSynced_ListReady'): this;
    (event: 'CompletedTasksSynced_FetchingTasks'): this;
    (event: 'CompletedTasksSynced_TasksFetched'): this;
    (event: 'CompletedTasksSynced_TasksCached'): this;
    (event: 'CompletedTasksSynced_SyncingThreadsToTasks'): this;
    (event: 'CompletedTasksSynced_ThreadsToTasksSynced'): this;
    (event: 'CompletedTasksSynced_SyncingTasksToThreads'): this;
    (event: 'CompletedTasksSynced_TasksToThreadsSynced'): this;
    (event: 'CompletedTasksSynced_SyncingCompletedThreads'): this;
    (event: 'CompletedTasksSynced_CompletedThreadsSynced'): this;
    (event: 'CompletedTasksSynced_SyncingCompletedTasks'): this;
    (event: 'CompletedTasksSynced_Any'): this;
    (event: 'CompletedTasksSynced_ThreadsFetched'): this;
    (event: 'CompletedTasksSynced_MsgsFetched'): this;
    (event: 'CompletedTasksSynced_Exception'): this;
    (event: 'ThreadsFetched_Enabled'): this;
    (event: 'ThreadsFetched_Syncing'): this;
    (event: 'ThreadsFetched_Synced'): this;
    (event: 'ThreadsFetched_Restart'): this;
    (event: 'ThreadsFetched_PreparingList'): this;
    (event: 'ThreadsFetched_ListReady'): this;
    (event: 'ThreadsFetched_FetchingTasks'): this;
    (event: 'ThreadsFetched_TasksFetched'): this;
    (event: 'ThreadsFetched_TasksCached'): this;
    (event: 'ThreadsFetched_SyncingThreadsToTasks'): this;
    (event: 'ThreadsFetched_ThreadsToTasksSynced'): this;
    (event: 'ThreadsFetched_SyncingTasksToThreads'): this;
    (event: 'ThreadsFetched_TasksToThreadsSynced'): this;
    (event: 'ThreadsFetched_SyncingCompletedThreads'): this;
    (event: 'ThreadsFetched_CompletedThreadsSynced'): this;
    (event: 'ThreadsFetched_SyncingCompletedTasks'): this;
    (event: 'ThreadsFetched_CompletedTasksSynced'): this;
    (event: 'ThreadsFetched_Any'): this;
    (event: 'ThreadsFetched_MsgsFetched'): this;
    (event: 'ThreadsFetched_Exception'): this;
    (event: 'MsgsFetched_Enabled'): this;
    (event: 'MsgsFetched_Syncing'): this;
    (event: 'MsgsFetched_Synced'): this;
    (event: 'MsgsFetched_Restart'): this;
    (event: 'MsgsFetched_PreparingList'): this;
    (event: 'MsgsFetched_ListReady'): this;
    (event: 'MsgsFetched_FetchingTasks'): this;
    (event: 'MsgsFetched_TasksFetched'): this;
    (event: 'MsgsFetched_TasksCached'): this;
    (event: 'MsgsFetched_SyncingThreadsToTasks'): this;
    (event: 'MsgsFetched_ThreadsToTasksSynced'): this;
    (event: 'MsgsFetched_SyncingTasksToThreads'): this;
    (event: 'MsgsFetched_TasksToThreadsSynced'): this;
    (event: 'MsgsFetched_SyncingCompletedThreads'): this;
    (event: 'MsgsFetched_CompletedThreadsSynced'): this;
    (event: 'MsgsFetched_SyncingCompletedTasks'): this;
    (event: 'MsgsFetched_CompletedTasksSynced'): this;
    (event: 'MsgsFetched_ThreadsFetched'): this;
    (event: 'MsgsFetched_Any'): this;
    (event: 'MsgsFetched_Exception'): this;
    (event: 'Exception_Enabled'): this;
    (event: 'Exception_Syncing'): this;
    (event: 'Exception_Synced'): this;
    (event: 'Exception_Restart'): this;
    (event: 'Exception_PreparingList'): this;
    (event: 'Exception_ListReady'): this;
    (event: 'Exception_FetchingTasks'): this;
    (event: 'Exception_TasksFetched'): this;
    (event: 'Exception_TasksCached'): this;
    (event: 'Exception_SyncingThreadsToTasks'): this;
    (event: 'Exception_ThreadsToTasksSynced'): this;
    (event: 'Exception_SyncingTasksToThreads'): this;
    (event: 'Exception_TasksToThreadsSynced'): this;
    (event: 'Exception_SyncingCompletedThreads'): this;
    (event: 'Exception_CompletedThreadsSynced'): this;
    (event: 'Exception_SyncingCompletedTasks'): this;
    (event: 'Exception_CompletedTasksSynced'): this;
    (event: 'Exception_ThreadsFetched'): this;
    (event: 'Exception_MsgsFetched'): this;
}