// Generated by CoffeeScript 1.7.1
(function() {
  var CLIENT_ID, CLIENT_SECRET, SERVICE_ACCOUNT_EMAIL, SERVICE_ACCOUNT_KEY_FILE, client, googleapis, jwt, oauth2;

  googleapis = require('googleapis');

  CLIENT_ID = '900809192866-q9cv7gnn2d66qfhhjk3bntofiu8qabv0.apps.googleusercontent.com';

  CLIENT_SECRET = 'notasecret';

  oauth2 = new googleapis.OAuth2Client(CLIENT_ID, CLIENT_SECRET, "postmessage");

  SERVICE_ACCOUNT_EMAIL = "900809192866-q9cv7gnn2d66qfhhjk3bntofiu8qabv0@developer.gserviceaccount.com";

  SERVICE_ACCOUNT_KEY_FILE = "googleapi-privatekey.pem";

  jwt = new googleapis.auth.JWT(SERVICE_ACCOUNT_EMAIL, SERVICE_ACCOUNT_KEY_FILE, null, ["https://www.googleapis.com/auth/tasks"]);

  client = void 0;

  googleapis.discover("tasks", "v1").execute(function(err, data) {
    client = data;
    return jwt.authorize(function(err, result) {
      oauth2.setCredentials({
        access_token: result.access_token
      });
      return client.tasks.tasklists.list().withAuthClient(oauth2).execute(function(err, body) {
        debugger;
        return console.log(body);
      });
    });
  });

}).call(this);
