// Generated by CoffeeScript 1.8.0
(function() {
  var Sync, async, go, main, settings, suspend, sync;

  require('./bootstrap/bootstrap');

  settings = require('../settings');

  suspend = require('suspend');

  sync = require('./sync/sync');

  Sync = sync.Sync;

  go = suspend.resume;

  async = suspend.async;

  Object.extend(settings, {
    gmail_max_results: 300
  });

  main = suspend(function() {
    return new Sync(settings);
  });

  main();

}).call(this);

//# sourceMappingURL=app.js.map
